### ISSUE TITLE
Reporting an issue in Table3.py

### ISSUE THREAD

**Issue by nivi1501** [AnPelec/t-wise-ind-SPN#1]
I have made a modification to line 63 of the Table3.py file to address an error related to a missing argument. Previously, the code was as follows:

y = F.Add(INV(inter_value, F), INV(key, F))

I have updated it to:

y = F.Add(INV(inter_value, n, F), INV(key, n, F))

Using this, I am able to generate the accurate Table3 values.

**Comment by AnPelec** [comment]
Thank you for catching this, I have fixed this error.

**Comment by apelecan** [comment]
Thank you for catching this, the error is now fixed.
